name: Build and Release

on:
  workflow_dispatch: 

permissions: 
  contents: write

jobs:
  build:
    name: Build for all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
          - os: macos-latest
            platform: ios
          - os: windows-latest
            platform: windows

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --release --no-codesign 

      - name: Build Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --release

      - name: Archive Windows
        if: matrix.platform == 'windows'
        shell: bash
        run: |
          cd build/windows/runner/Release/
          tar -a -c -f ../../../../windows-release.zip *

      - name: Archive iOS
        if: matrix.platform == 'ios'
        shell: bash
        run: |
          cd build/ios/iphoneos/
          zip -r ../../../ios-release.zip Runner.app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            ios-release.zip
            windows-release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build v${{ github.run_number }}
          files: |
            **/app-release.apk
            **/ios-release.zip
            **/windows-release.zip