name: Build iOS for Sideloadly

on:
  workflow_dispatch: # Запуск вручную кнопкой в Actions

permissions:
  contents: write

jobs:
  build-ios:
    name: Create IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS Project
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA for Sideloadly
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app-release.ipa Payload
          rm -rf Payload

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ios-v${{ github.run_number }}
          name: iOS Build v${{ github.run_number }}
          files: app-release.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}