name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
          - os: macos-latest
            platform: ios
          - os: windows-latest
            platform: windows

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Desktop and Fix Project
        run: |
          flutter config --enable-windows-desktop
          flutter pub get

      # Сборка Android
      - name: Build Android
        if: matrix.platform == 'android'
        run: flutter build apk --release

      # Сборка iOS и конвертация в .ipa для Sideloadly
      - name: Build iOS
        if: matrix.platform == 'ios'
        run: |
          flutter build ios --release --no-codesign
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app-release.ipa Payload
          rm -rf Payload

      # Сборка Windows
      - name: Build Windows
        if: matrix.platform == 'windows'
        run: |
          flutter build windows --release
          compress-archive -Path build/windows/runner/Release/* -DestinationPath windows-release.zip
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/*.apk
            app-release.ipa
            windows-release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Build v${{ github.run_number }}
          files: |
            **/*.apk
            **/*.ipa
            **/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}